config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root :to => "admin/main#index", as: :authenticated_root
  end

  root 'pages#index'
  get "program", to: 'pages#program', as: :program
  get 'registration', to: 'admin/registrations#new'
  
  namespace :admin do
     root :to => "main#index"
     
     get 'report', to: 'main#report'
     get 'search', to: 'main#search'
     
     resources :users
     resources :registrations
  end

  devise_for :users
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  #data for select
  DAYS = [3, 2, 1]
  CITIES = [
      'Banska Bystrica',
      'Bratislava',
      'Brno',
      'Ceske Budejovice',
      'Frydek Mistek',
      'Hradec Kralove',
      'Jicin',
      'Kosice',
      'Liberec',
      'Martin',
      'Mlada Boleslav',
      'Olomouc',
      'Ostrava',
      'Pardubice',
      'Plzen',
      'Prague',
      'Trebic',
      'Trencin',
      'Zilina',
      'Zlin'
  ]

  COUNTRIES = ['Czech Republic', 'Slovakia']
  ARRIVING = ['Friday', 'Saturday', 'Sunday']
  

  #pagination
  self.per_page = 10
  
  validates :name, :last_name, :email, :phone, :country, :city, :gender, :arriving, presence: true
  validates :name, :last_name, :email, length: { in: 2..30 }
  validates :phone, numericality: true, length: { minimum: 9, maximum: 15 }
  validates :days, :member, :need_place, numericality: { only_integer: true }
  validate  :email_regex
  before_save { self.email = email.downcase }
  
  def full_name
    "#{self.name} #{self.last_name}"
  end

  def self.search(search)
    where("name ilike ? or last_name ilike ? or concat(name, ' ', last_name) ilike ? or email ilike ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
  
  private 
  
  def filter(filtering_params)
    results = self.where(nil)
    filtering_params.each do |key, value|
      results = results.public_send(key, value) if value.present?
    end
    results
  end
  
  def email_regex
    if email.present? and not email.match(/\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/)
      errors.add :email, "This is not a valid email format"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  before_destroy :check_users

  private

  def check_users
    false if User.count == 1
  end
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
  before_action :authenticate_user!

  def index
    @all = Registration.all.count
    @need_place = Registration.where(need_place: true).count
    @man = Registration.where(gender: 'male').count
    @woman = Registration.where(gender: 'female').count
    @friday = Registration.where(arriving: 'Friday').count
    @saterday = Registration.where(arriving: 'Saturday').count

  end

  def report
  end

  def search
  end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create]

  # GET /registrations
  def index
    if params[:search]
      @registrations = Registration.search(params[:search]).paginate(page: params[:page]).order("id DESC")
      @params = params[:search]
    else
      @registrations = Registration.paginate(page: params[:page]).order("id DESC")
    end

    respond_to do |format|
      format.html
      format.js { @params }
      format.xls {headers["Content-Disposition"] = "attachment; filename=\"registrations_#{Time.now.to_i}.xls\"" }
    end
  end

  # GET /registrations/1
  def show
  end

  # GET /registrations/new
  def new
    @registration = Registration.new
  end

  # GET /registrations/1/edit
  def edit
  end

  # POST /registrations
  def create
    @registration = Registration.new(registration_params)
    respond_to do |format|
      if @registration.save
        format.html { redirect_to admin_registrations_path, notice: 'Registration was successfully created.' }
        format.js {@msg = "Thank you for your registration! We're excited to see you :)"}
      else
        format.html {
          flash.now[:alert] = @registration.errors.full_messages.to_sentence
          render "new"
        }
        format.js
      end
    end
  end

  # PATCH/PUT /registrations/1
  def update
    if @registration.update(registration_params)
      redirect_to admin_registration_path(@registration), notice: 'Registration was successfully updated.'
    else
      flash[:alert] = @registration.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /registrations/1
  def destroy
    @registration.destroy!
      redirect_to admin_registrations_url, notice: 'Registration was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @registration = Registration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_params
      params.require(:registration).permit(:name, :last_name, :email, :phone, :country, :city, :member, :need_place, :days, :comment, :gender, :arriving)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /admin/users
  def index
    @users = User.all
  end

  # GET /admin/users/1
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path, notice: 'User has been sucessfully created'
      else
        render :new, alert: @user.errors.full_messages.to_sentence
      end
 
  end

  # PATCH/PUT /admin/users/1
  def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit, alert: @user.errors.full_messages.to_sentence
      end
   end

  # DELETE /admin/users/1
  def destroy
    if User.count == 1 || current_user.id == @user.id
      flash[:alert] = 'You can\'t delete yourself'
    else
      @user.destroy!
      flash[:notice] = 'User was successfully destroyed.'
    end

    redirect_to admin_users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :last_name, :password, :email, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'admin'
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'application'
  def index
  end

  def program
    send_file(
        "#{Rails.root}/public/sc.pdf",
        filename: "ysa_weekend_prague_program.pdf",
        type: "application/pdf"
    )
  end
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def set_active_nav(cntr)
    'active' if cntr == params[:controller]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/main/index.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Summary information
  .panel-body
    %table.table
      %tr
        %th
          All registrations
        %td
          = @all
      %tr
        %th
          Need accommodation
        %td
          = @need_place
      %tr
        %th
          Men
        %td
          = @man
      %tr
        %th
          Women
        %td
          = @woman
      %tr
        %th
          Arriving on Friday
        %td
          = @friday
      %tr
        %th
          Arriving on Saturday
        %td
          = @saterday

app/views/admin/users/_form.html.haml
= form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'form-control'
  .form-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'form-control'
  .form-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :class => 'form-control'
  .form-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'form-control'
  = f.submit :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn btn-default'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:last_name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, admin_user_path(user)
        %td= user.name
        %td= user.last_name
        %td= user.created_at.strftime("%B %d, %Y at %H:%M")
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_user_path, :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @user.last_name


= link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/_tmp.html.haml
%h1
  Site is under development
%h3
  Information about the event will be here soon :)
  
%small= params[:action]+" page"

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "YsaActivity"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "admin"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "admin"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'YSA WEEKEND', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
          - if user_signed_in?
            %ul.nav.navbar-nav.pull-right
              %li= link_to "Log out[#{current_user.name}]", destroy_user_session_path, method: :delete

    .container
      .row
        %div{class: user_signed_in? ? 'col-md-9' : 'col-md-12'}
          = bootstrap_flash
          = yield
        .col-md-3
          - if user_signed_in?
            %br
            %ul.nav.nav-pills.nav-stacked
              %li{class: set_active_nav('admin/main')}
                = link_to root_path do
                  %i.fa.fa-tachometer.fa-fw
                  Overview
              %li{class: set_active_nav('admin/registrations')}
                = link_to  admin_registrations_path do
                  %i.fa.fa-list-alt.fa-fw
                  Manage registrations
              %li{class: set_active_nav('admin/users')}
                = link_to admin_users_path do
                  %i.fa.fa-users.fa-fw
                  Admins

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "YSA WEEKEND PRAGUE"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = javascript_include_tag "//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
    = stylesheet_link_tag "application"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  %body#page-top.index
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header.page-scroll
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand.page-scroll{:href => "#page-top"} YSA WEEKEND PRAGUE
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li.hidden
              %a{:href => "#page-top"}
            %li
              %a.page-scroll{:href => "#information"} Information
            %li
              %a.page-scroll{:href => "#program"} Program
            %li
              %a.page-scroll{:href => "#contactInfo"} Contact
            %li
              %a.page-scroll{:href => "#contact"} Registration

    = yield
    %footer
      .container
        .row
          .col-md-4
            %span.copyright Copyright &copy; YSA WEEKEND 2014
          .col-md-4
            %ul.list-inline.social-buttons
              %li
                %a{:href => "#"}
                  %i.fa.fa-twitter
              %li
                %a{:href => "#"}
                  %i.fa.fa-facebook
              %li
                %a{:href => "#"}
                  %i.fa.fa-linkedin
    = javascript_include_tag "application"

app/views/notify/welcome.text.haml
Hello,
= @registration.full_name

Thank you for your registration. We are excited to see you.
If you have some question, feel free to write us.

See you soon :)

app/views/pages/_code.html.haml
%p{:align => "CENTER"}
  %span{:style => "font-family: Times, serif; font-size: medium;"}
    %span{:style => "font-family: Times, serif;"}
      %span{:style => "font-family: Times, serif;"}
        %span{:style => "font-family: Times, serif;"} Young Single Adult Prague Weekend 2014
%p
  %span{:style => "font-family: Times, serif; font-size: medium;"}
    %span{:style => "font-family: Times, serif;"} All participants of the Young Single Adult Weekend, are expected to abide by the standards of the Church of Jesus Christ of Latter-day Saints, for the security and safety of all involved.
%ul
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I have read and am familiar with the standards as described in the
        %span{:style => "font-family: Times, serif;"}
          %strong For the Strength of Youth
        %span{:style => "font-family: Times, serif;"} pamphlet, and agree to abide by them throughout the time of the conference.
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I have read the standards included in the
        %span{:style => "font-family: Times, serif;"}
          %strong Word of Wisdom
        %span{:style => "font-family: Times, serif;"} and agree to abide by them.
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %a{:name => "_GoBack"}
        %span{:style => "font-family: Times, serif;"}
          %span{:style => "font-family: Times, serif;"} I will keep the
          %span{:style => "font-family: Times, serif;"}
            %strong Law of Chastity
          %span{:style => "font-family: Times, serif;"} .
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I will closely follow the
        %span{:style => "font-family: Times, serif;"}
          %strong dress code
        %span{:style => "font-family: Times, serif;"} at all times.*
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I will use only
        %span{:style => "font-family: Times, serif;"}
          %strong clean and respectful language
        %span{:style => "font-family: Times, serif;"} .
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I will
        %span{:style => "font-family: Times, serif;"}
          %strong display friendship and maintain behavior appropriate to the spirit of the Church conference.
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I will follow the instructions of the weekend organizers/Prague District leadership.
  %li
    %p
      %span{:style => "font-family: Times, serif; font-size: medium;"}
        %span{:style => "font-family: Times, serif;"} I am aware that breaking rules and/or instructions may result in suspension from participation.
%p
  %span{:style => "font-family: Times, serif; font-size: medium;"}
    %span{:style => "font-family: Times, serif;"} * The dress code is an important part of the conference and applies to both men and women. At no time during the conference program, activities, dances or free time is it allowable to wear clothing, which is &lsquo;see-through&rsquo; or revealing in any way. Shorts and skirts must be knee-length or longer. Shirts and blouses must cover waist and shoulders and must not be low-cut in the front or back. These guidelines also apply to sports activities attire. If the attire is shorter than the knee-length or too revealing the participant will be asked to change into appropriate clothing or, in extreme cases, be excluded from participating in the activity.&nbsp;

app/views/pages/contact.html.haml
= render 'layouts/tmp'

app/views/pages/index.html.haml
%header
  .container
    .intro-text
      .intro-lead-in YOUNG SINGLE ADULT WEEKEND
      .intro-lead-in 3 - 5 October
      .intro-heading Prague 2014
      %a.page-scroll.btn.btn-xl{:href => "#contact"} Registration
/ Services Section
%section#information
  .container
    .row
      .col-lg-12.text-center
        %h2.section-heading Information / Informace
        %h3.section-subheading.text-muted
          I have labored without ceasing, that I might bring souls unto repentance;
          %br
          %br
          that I might bring them to taste of the exceeding joy of which I did taste
          %br
          %br
          %br
          „…od oné doby až do nynějška jsem bez ustání pracoval, abych mohl přiváděti duše ku pokání;
          %br
          %br
          abych je mohl přiváděti k tomu, aby okusily onu nesmírnou radost, kterou jsem okusil já…“
    .row.text-center
      .info-text.text-muted
        %p.info-text
          The Prague District is inviting you to the young single adult prague weekend which will be full of fun, spirituality, great experiences and friends.
          Not a member of this Church? Please come with one of our members!
        %p.info-text
          Anyone who is between the ages of
          %strong
            18 and 30 years, not married and agrees to keep our
          %strong= link_to 'Code of Conduct', '#portfolioModal2', data:{toggle: 'modal'}
          can come to the activities and join us.
          Think about your clothes and dress according to the church standards
          See and follow:
          %br
          = link_to 'The Strength of Youth pamphlet',
          "https://www.lds.org/manual/for-the-strength-of-youth-fulfilling-our-duty-to-god?lang=eng&query=strength+of+youth",
          target: '_blank'
    .row.text-center
      .info-text.text-muted
        %p.info-text
          Okrsek praha vás zve napražský víkend mladých svobodných dospělých, který bude plný zábavy, duchovních věcí, úžasných zkušeností a přátel.
          Nejste členem této církve? prosím přijďte s jedním z našich členů!
        %p.info-text
          %strong
            Kdokoliv ve věku od 18 do 30ti let,
            svobodný a kdo souhlasí s dodržováním našeho
          %strong= link_to 'kodexu chování', '#portfolioModal4', data:{toggle: 'modal'}
          může přijít a připojit se k nám!
          Popřemýslejte o vhodném oblečení v souladu s církevními měřítky
          Podívejte se a řiďte se podle:
          %br
          = link_to 'brožurky pro posílení mládeže',
          "https://www.lds.org/manual/for-the-strength-of-youth-fulfilling-our-duty-to-god?lang=eng&query=strength+of+youth",
          target: '_blank'

    %hr
    .row
      .col-md-4.col-sm-6.portfolio-item
        .portfolio-caption
          %h4.text-center TIME / ČAS
          %p.text-muted
            Friday— arrivals around 17:00
            The end will be after Sunday church
          %p.text-muted
            Pátek – příjezd kolem 17:00
            Konec po nedělním shromáždění
      .col-md-4.col-sm-6.portfolio-item
        .portfolio-caption
          %h4.text-center FOOD / JÍDLO
          %p.text-muted
            All the food will be provided by organisers of the Activity.
            %br
            %strong No food will be provided on Sunday (Fast Sunday)
          %p.text-muted
            Prosím uveďte jakékoliv alergie při vyplňování registrace online. veškeré jídlo bude poskytnuto.
            %br
            %strong Žádné jídlo nebude poskytnuto v neděli (Postní Neděle)
      .col-md-4.col-sm-6.portfolio-item
        .portfolio-caption
          %h4.text-center ACCOMMODATION / UBYTOVÁNÍ
          %p.text-muted
            If you send your registrations by
            %strong
              20.09.2014
            %br
            All the housing will be prepared for you with families in the branch.
          %p.text-muted
            Pokud pošlete svou registraci do
            %strong 20.9.2014
            %br
            Veškeré ubytování bude pro vás připraveno u rodin v odbočce.


/ Portfolio Grid Section
%section#program.bg-light-gray
  .container
    .row
      .col-lg-12.col-md-12.text-center
        %h2.section-heading Program
        %h3.section-subheading.text-muted „ …I have labored without ceasing, that I might bring souls unto repentance; that I might bring them to taste of the exceeding joy of which I did taste …“
    .row

      .col-md-4.col-sm-6.col-md-offset-4.col-sm-offset-6.portfolio-item
      .col-md-4.col-sm-6.col-md-offset-4.col-sm-offset-6.portfolio-item
        %a.portfolio-link{"data-toggle" => "modal", :href => "#portfolioModal3"}
          = image_tag 'sc.jpg', width: '400px', height: '260px', class: 'img-responsive'
        .portfolio-caption
          %h4.text-center Activity Program
          %p.text-center.text-muted (Click on the image to make it bigger)
      .col-md-4.col-sm-6.portfolio-item


/ About Section
%section#contactInfo
  .container
    .row
      .col-lg-12.clo-md-12.text-center
        %h2.section-heading Contact
        %h3.section-subheading.text-muted You can reach us by this contact information
    .row
      %p.info-text.text-muted.text-center
        If you have any questions, feel free to write us an email:
        %strong
          = link_to 'ysapraha2014@gmail.com', 'mailto:ysapraha2014@gmail.com'
      %p.info-text.text-muted.text-center
        %strong Address:
        Prague’s chapel, Milady Horákové 85/95, Praha 17000
%section#contact
  .container
    .row
      .col-lg-12.col-md-12.text-center
        %h2.section-heading Registration
        %h3.section-subheading.text-muted You should be registered before go to the activity
    .row
      .col-lg-6.col-lg-offset-3.col-md-8.col-lg-offset-4
        = link_to 'Open Registration Form', '#portfolioModal1', class: 'btn btn-xl btn-lg btn-md btn-primary btn-block', data:{toggle: 'modal'}


#portfolioModal1.portfolio-modal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-content
    #close-form.close-modal{"data-dismiss" => "modal"}
      .lr
        .rl
    .container
      .row
        .col-lg-10.col-lg-offset-1
          .modal-body
            %h2.text-center Registration Form
            #msgs
            .panel.panel-default.col-md-12.col-sm-12.reg-form
              .col-md-10.col-sm-12.col-md-offset-1
                = render 'admin/registrations/frontend_form'

#portfolioModal2.portfolio-modal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-content
    .close-modal{"data-dismiss" => "modal"}
      .lr
        .rl
    .container
      .row
        .col-lg-10.col-lg-offset-1
          .modal-body
            %h2.text-center Code of Conduct
            = render 'code'
#portfolioModal3.portfolio-modal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-content
    .close-modal{"data-dismiss" => "modal"}
      .lr
        .rl
    .container
      .row
        .col-lg-10.col-lg-offset-1
          .modal-body
            %h2.text-center YSA WEEKEND PROGRAM
            .col-md-2.col-md-offset-5
              = link_to 'PDF file', program_path, class: 'btn btn-primary btn-block', target: '_blank'
            = image_tag 'sc.jpg', class: 'img-responsive'
#portfolioModal4.portfolio-modal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-content
    .close-modal{"data-dismiss" => "modal"}
      .lr
        .rl
    .container
      .row
        .col-lg-10.col-lg-offset-1
          .modal-body
            = image_tag 'cd.jpg'


= render 'admin/registrations/success_reg'

app/views/pages/info.html.haml
= render 'layouts/tmp'

app/views/pages/registration.html.haml
%h1 Pages#registration
%p Find me in app/views/pages/registration.html.haml